<a href="https://colab.research.google.com/github/ravinasha/mac/blob/main/embedding_in_rnn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
docs = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [2]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
len(tokenizer.word_index)

17

In [5]:
sequences = tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [6]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences,padding='post')
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [9]:
from keras.models import Sequential
from keras.layers import Embedding

model = Sequential()
model.add(Embedding(input_dim=17, output_dim=2, input_length=5))

model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 2)              34        
                                                                 
Total params: 34 (136.00 Byte)
Trainable params: 34 (136.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
model.compile('adam','accuracy')

In [12]:
import numpy as np

# Example input sequences
sequences = np.array([
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14],
    [15, 16, 17, 17, 17]  # This sequence contains invalid indices
])

# Clamping the values to be within the valid range [0, 16]
sequences = np.clip(sequences, 0, 16)

# Now predict using the sanitized sequences
pred = model.predict(sequences)
print(pred)


1/1 [==============================] - 0s 46ms/step
[[[ 0.03865721  0.03931599]
  [ 0.02728136  0.02951945]
  [ 0.0252508   0.04794214]
  [ 0.02891773  0.03300823]
  [ 0.0204661   0.04159386]]

 [[-0.04119104 -0.04059808]
  [-0.0471501   0.04211609]
  [-0.00025433 -0.04800048]
  [-0.01456873  0.0494017 ]
  [ 0.00586158  0.01259717]]

 [[ 0.01412246 -0.0400728 ]
  [-0.00865778 -0.043476  ]
  [-0.01747532  0.01323735]
  [ 0.00852964 -0.03422325]
  [ 0.04161345 -0.00860014]]

 [[-0.02720798  0.04910043]
  [ 0.01119341  0.02938596]
  [ 0.01119341  0.02938596]
  [ 0.01119341  0.02938596]
  [ 0.01119341  0.02938596]]]


In [13]:
from keras.datasets import imdb
from keras.preprocessing.text import Tokenizer
from keras.utils import pad_sequences
from keras import Sequential
from keras.layers import Dense,SimpleRNN,Embedding,Flatten

In [14]:
(X_train,y_train),(X_test,y_test) = imdb.load_data()

17464789/17464789 [==============================] - 0s 0us/step


In [15]:
X_train = pad_sequences(X_train,padding='post',maxlen=50)
X_test = pad_sequences(X_test,padding='post',maxlen=50)

In [16]:
X_train.shape

(25000, 50)

In [18]:
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense

model = Sequential()
model.add(Embedding(input_dim=10000, output_dim=2, input_length=50))
model.add(SimpleRNN(32, return_sequences=False))
model.add(Dense(1, activation='sigmoid'))

model.summary()


Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_2 (Embedding)     (None, 50, 2)             20000     
                                                                 
 simple_rnn (SimpleRNN)      (None, 32)                1120      
                                                                 
 dense (Dense)               (None, 1)                 33        
                                                                 
Total params: 21153 (82.63 KB)
Trainable params: 21153 (82.63 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
from keras.preprocessing.sequence import pad_sequences
import numpy as np

# Example sequences (replace with your actual data)
X_train = [
    [1, 2, 3, 4, 5, 9999],
    [6, 7, 8, 9, 10, 11]
    # Add more sequences as needed
]

X_test = [
    [1, 2, 3, 4, 5, 9999],
    [6, 7, 8, 9, 10, 11]
    # Add more sequences as needed
]

# Padding or truncating sequences to length 50
X_train = pad_sequences(X_train, maxlen=50, padding='post', truncating='post')
X_test = pad_sequences(X_test, maxlen=50, padding='post', truncating='post')

# Ensure y_train and y_test are correctly defined (example)
y_train = np.array([0, 1])  # Adjust to match the length of X_train
y_test = np.array([1, 0])   # Adjust to match the length of X_test

# Check the shapes of the arrays to confirm they match
print("X_train shape:", X_train.shape)  # Should be (num_samples, 50)
print("y_train shape:", y_train.shape)
print("X_test shape:", X_test.shape)    # Should be (num_samples, 50)
print("y_test shape:", y_test.shape)

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])

# Fit the model
history = model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))


X_train shape: (2, 50)
y_train shape: (2,)
X_test shape: (2, 50)
y_test shape: (2,)
Epoch 1/5
1/1 [==============================] - 4s 4s/step - loss: 0.6870 - acc: 0.5000 - val_loss: 0.7190 - val_acc: 0.0000e+00
Epoch 2/5
1/1 [==============================] - 0s 90ms/step - loss: 0.6681 - acc: 1.0000 - val_loss: 0.7440 - val_acc: 0.0000e+00
Epoch 3/5
1/1 [==============================] - 0s 58ms/step - loss: 0.6449 - acc: 1.0000 - val_loss: 0.7803 - val_acc: 0.0000e+00
Epoch 4/5
1/1 [==============================] - 0s 70ms/step - loss: 0.6131 - acc: 1.0000 - val_loss: 0.8429 - val_acc: 0.0000e+00
Epoch 5/5
1/1 [==============================] - 0s 84ms/step - loss: 0.5638 - acc: 1.0000 - val_loss: 0.9502 - val_acc: 0.0000e+00
